# .github/workflows/docker-publish.yml

name: Build and Push Docker Image to Docker Hub

# 触发器：当代码被推送到 main 分支时运行
on:
  push:
    branches: [ "main" ]

jobs:
  build_and_push:
    # 运行环境：使用最新的 Ubuntu
    runs-on: ubuntu-latest

    steps:
      # 步骤 1: 检出仓库代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 步骤 2: 设置 QEMU，用于多平台构建 (可选，但推荐)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # 步骤 3: 设置 Docker Buildx，这是 Docker 的下一代构建工具
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 步骤 4: 登录到 Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # 步骤 5: 构建并推送 Docker 镜像
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          with:
          push: true
          tags: bofbef/decode:latest
          platforms: linux/amd64,linux/arm64
